FROM node:lts-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && chown -R node:node /app

EXPOSE 5173

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER node

ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
