/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotersRouteImport } from './routes/voters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StateRouteImport } from './routes/$state'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotersIndexRouteImport } from './routes/voters/index'
import { Route as LookupIndexRouteImport } from './routes/lookup/index'
import { Route as ElectionsIndexRouteImport } from './routes/elections/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VotersVoterIdRouteImport } from './routes/voters/$voterId'
import { Route as LookupResultsRouteImport } from './routes/lookup/results'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as ElectionsElectionIdRouteImport } from './routes/elections/$electionId'
import { Route as ElectionsElectionDateRouteImport } from './routes/elections/$electionDate'
import { Route as DistrictsDistrictIdRouteImport } from './routes/districts/$districtId'
import { Route as CountiesCountyIdRouteImport } from './routes/counties/$countyId'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates/$candidateId'
import { Route as ElectionsElectionDateIndexRouteImport } from './routes/elections/$electionDate/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminImportsIndexRouteImport } from './routes/admin/imports/index'
import { Route as AdminGeocodingIndexRouteImport } from './routes/admin/geocoding/index'
import { Route as AdminExportsIndexRouteImport } from './routes/admin/exports/index'
import { Route as AdminElectionsIndexRouteImport } from './routes/admin/elections/index'
import { Route as AdminAnalysisIndexRouteImport } from './routes/admin/analysis/index'
import { Route as ElectionsElectionDateElectionIdRouteImport } from './routes/elections/$electionDate/$electionId'
import { Route as DistrictsTypeNameRouteImport } from './routes/districts/$type/$name'
import { Route as CountiesStateCountyRouteImport } from './routes/counties/$state/$county'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminElectionsImportFeedRouteImport } from './routes/admin/elections/import-feed'
import { Route as AdminElectionsCreateRouteImport } from './routes/admin/elections/create'
import { Route as AdminElectionsElectionIdRouteImport } from './routes/admin/elections/$electionId'
import { Route as AdminAnalysisRunIdRouteImport } from './routes/admin/analysis/$runId'
import { Route as DistrictsStateTypeNameRouteImport } from './routes/districts/$state/$type/$name'
import { Route as DistrictsStateCountyTypeNameRouteImport } from './routes/districts/$state/$county/$type/$name'

const VotersRoute = VotersRouteImport.update({
  id: '/voters',
  path: '/voters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StateRoute = StateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotersIndexRoute = VotersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VotersRoute,
} as any)
const LookupIndexRoute = LookupIndexRouteImport.update({
  id: '/lookup/',
  path: '/lookup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsIndexRoute = ElectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElectionsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VotersVoterIdRoute = VotersVoterIdRouteImport.update({
  id: '/$voterId',
  path: '/$voterId',
  getParentRoute: () => VotersRoute,
} as any)
const LookupResultsRoute = LookupResultsRouteImport.update({
  id: '/lookup/results',
  path: '/lookup/results',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsElectionIdRoute = ElectionsElectionIdRouteImport.update({
  id: '/$electionId',
  path: '/$electionId',
  getParentRoute: () => ElectionsRoute,
} as any)
const ElectionsElectionDateRoute = ElectionsElectionDateRouteImport.update({
  id: '/$electionDate',
  path: '/$electionDate',
  getParentRoute: () => ElectionsRoute,
} as any)
const DistrictsDistrictIdRoute = DistrictsDistrictIdRouteImport.update({
  id: '/districts/$districtId',
  path: '/districts/$districtId',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesCountyIdRoute = CountiesCountyIdRouteImport.update({
  id: '/counties/$countyId',
  path: '/counties/$countyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsElectionDateIndexRoute =
  ElectionsElectionDateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ElectionsElectionDateRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportsIndexRoute = AdminImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeocodingIndexRoute = AdminGeocodingIndexRouteImport.update({
  id: '/geocoding/',
  path: '/geocoding/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsIndexRoute = AdminExportsIndexRouteImport.update({
  id: '/exports/',
  path: '/exports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsIndexRoute = AdminElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalysisIndexRoute = AdminAnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => AdminRoute,
} as any)
const ElectionsElectionDateElectionIdRoute =
  ElectionsElectionDateElectionIdRouteImport.update({
    id: '/$electionId',
    path: '/$electionId',
    getParentRoute: () => ElectionsElectionDateRoute,
  } as any)
const DistrictsTypeNameRoute = DistrictsTypeNameRouteImport.update({
  id: '/districts/$type/$name',
  path: '/districts/$type/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesStateCountyRoute = CountiesStateCountyRouteImport.update({
  id: '/counties/$state/$county',
  path: '/counties/$state/$county',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsImportFeedRoute =
  AdminElectionsImportFeedRouteImport.update({
    id: '/elections/import-feed',
    path: '/elections/import-feed',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminElectionsCreateRoute = AdminElectionsCreateRouteImport.update({
  id: '/elections/create',
  path: '/elections/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsElectionIdRoute =
  AdminElectionsElectionIdRouteImport.update({
    id: '/elections/$electionId',
    path: '/elections/$electionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalysisRunIdRoute = AdminAnalysisRunIdRouteImport.update({
  id: '/analysis/$runId',
  path: '/analysis/$runId',
  getParentRoute: () => AdminRoute,
} as any)
const DistrictsStateTypeNameRoute = DistrictsStateTypeNameRouteImport.update({
  id: '/districts/$state/$type/$name',
  path: '/districts/$state/$type/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsStateCountyTypeNameRoute =
  DistrictsStateCountyTypeNameRouteImport.update({
    id: '/districts/$state/$county/$type/$name',
    path: '/districts/$state/$county/$type/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$state': typeof StateRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/elections': typeof ElectionsRouteWithChildren
  '/login': typeof LoginRoute
  '/voters': typeof VotersRouteWithChildren
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/elections/$electionDate': typeof ElectionsElectionDateRouteWithChildren
  '/elections/$electionId': typeof ElectionsElectionIdRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/lookup/results': typeof LookupResultsRoute
  '/voters/$voterId': typeof VotersVoterIdRoute
  '/admin/': typeof AdminIndexRoute
  '/elections/': typeof ElectionsIndexRoute
  '/lookup/': typeof LookupIndexRoute
  '/voters/': typeof VotersIndexRoute
  '/admin/analysis/$runId': typeof AdminAnalysisRunIdRoute
  '/admin/elections/$electionId': typeof AdminElectionsElectionIdRoute
  '/admin/elections/create': typeof AdminElectionsCreateRoute
  '/admin/elections/import-feed': typeof AdminElectionsImportFeedRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/counties/$state/$county': typeof CountiesStateCountyRoute
  '/districts/$type/$name': typeof DistrictsTypeNameRoute
  '/elections/$electionDate/$electionId': typeof ElectionsElectionDateElectionIdRoute
  '/admin/analysis/': typeof AdminAnalysisIndexRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/exports/': typeof AdminExportsIndexRoute
  '/admin/geocoding/': typeof AdminGeocodingIndexRoute
  '/admin/imports/': typeof AdminImportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/elections/$electionDate/': typeof ElectionsElectionDateIndexRoute
  '/districts/$state/$type/$name': typeof DistrictsStateTypeNameRoute
  '/districts/$state/$county/$type/$name': typeof DistrictsStateCountyTypeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$state': typeof StateRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/elections/$electionId': typeof ElectionsElectionIdRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/lookup/results': typeof LookupResultsRoute
  '/voters/$voterId': typeof VotersVoterIdRoute
  '/admin': typeof AdminIndexRoute
  '/elections': typeof ElectionsIndexRoute
  '/lookup': typeof LookupIndexRoute
  '/voters': typeof VotersIndexRoute
  '/admin/analysis/$runId': typeof AdminAnalysisRunIdRoute
  '/admin/elections/$electionId': typeof AdminElectionsElectionIdRoute
  '/admin/elections/create': typeof AdminElectionsCreateRoute
  '/admin/elections/import-feed': typeof AdminElectionsImportFeedRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/counties/$state/$county': typeof CountiesStateCountyRoute
  '/districts/$type/$name': typeof DistrictsTypeNameRoute
  '/elections/$electionDate/$electionId': typeof ElectionsElectionDateElectionIdRoute
  '/admin/analysis': typeof AdminAnalysisIndexRoute
  '/admin/elections': typeof AdminElectionsIndexRoute
  '/admin/exports': typeof AdminExportsIndexRoute
  '/admin/geocoding': typeof AdminGeocodingIndexRoute
  '/admin/imports': typeof AdminImportsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/elections/$electionDate': typeof ElectionsElectionDateIndexRoute
  '/districts/$state/$type/$name': typeof DistrictsStateTypeNameRoute
  '/districts/$state/$county/$type/$name': typeof DistrictsStateCountyTypeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$state': typeof StateRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/elections': typeof ElectionsRouteWithChildren
  '/login': typeof LoginRoute
  '/voters': typeof VotersRouteWithChildren
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/districts/$districtId': typeof DistrictsDistrictIdRoute
  '/elections/$electionDate': typeof ElectionsElectionDateRouteWithChildren
  '/elections/$electionId': typeof ElectionsElectionIdRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/lookup/results': typeof LookupResultsRoute
  '/voters/$voterId': typeof VotersVoterIdRoute
  '/admin/': typeof AdminIndexRoute
  '/elections/': typeof ElectionsIndexRoute
  '/lookup/': typeof LookupIndexRoute
  '/voters/': typeof VotersIndexRoute
  '/admin/analysis/$runId': typeof AdminAnalysisRunIdRoute
  '/admin/elections/$electionId': typeof AdminElectionsElectionIdRoute
  '/admin/elections/create': typeof AdminElectionsCreateRoute
  '/admin/elections/import-feed': typeof AdminElectionsImportFeedRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/counties/$state/$county': typeof CountiesStateCountyRoute
  '/districts/$type/$name': typeof DistrictsTypeNameRoute
  '/elections/$electionDate/$electionId': typeof ElectionsElectionDateElectionIdRoute
  '/admin/analysis/': typeof AdminAnalysisIndexRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/exports/': typeof AdminExportsIndexRoute
  '/admin/geocoding/': typeof AdminGeocodingIndexRoute
  '/admin/imports/': typeof AdminImportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/elections/$electionDate/': typeof ElectionsElectionDateIndexRoute
  '/districts/$state/$type/$name': typeof DistrictsStateTypeNameRoute
  '/districts/$state/$county/$type/$name': typeof DistrictsStateCountyTypeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$state'
    | '/about'
    | '/admin'
    | '/elections'
    | '/login'
    | '/voters'
    | '/candidates/$candidateId'
    | '/counties/$countyId'
    | '/districts/$districtId'
    | '/elections/$electionDate'
    | '/elections/$electionId'
    | '/invite/accept'
    | '/lookup/results'
    | '/voters/$voterId'
    | '/admin/'
    | '/elections/'
    | '/lookup/'
    | '/voters/'
    | '/admin/analysis/$runId'
    | '/admin/elections/$electionId'
    | '/admin/elections/create'
    | '/admin/elections/import-feed'
    | '/admin/users/create'
    | '/counties/$state/$county'
    | '/districts/$type/$name'
    | '/elections/$electionDate/$electionId'
    | '/admin/analysis/'
    | '/admin/elections/'
    | '/admin/exports/'
    | '/admin/geocoding/'
    | '/admin/imports/'
    | '/admin/users/'
    | '/elections/$electionDate/'
    | '/districts/$state/$type/$name'
    | '/districts/$state/$county/$type/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$state'
    | '/about'
    | '/login'
    | '/candidates/$candidateId'
    | '/counties/$countyId'
    | '/districts/$districtId'
    | '/elections/$electionId'
    | '/invite/accept'
    | '/lookup/results'
    | '/voters/$voterId'
    | '/admin'
    | '/elections'
    | '/lookup'
    | '/voters'
    | '/admin/analysis/$runId'
    | '/admin/elections/$electionId'
    | '/admin/elections/create'
    | '/admin/elections/import-feed'
    | '/admin/users/create'
    | '/counties/$state/$county'
    | '/districts/$type/$name'
    | '/elections/$electionDate/$electionId'
    | '/admin/analysis'
    | '/admin/elections'
    | '/admin/exports'
    | '/admin/geocoding'
    | '/admin/imports'
    | '/admin/users'
    | '/elections/$electionDate'
    | '/districts/$state/$type/$name'
    | '/districts/$state/$county/$type/$name'
  id:
    | '__root__'
    | '/'
    | '/$state'
    | '/about'
    | '/admin'
    | '/elections'
    | '/login'
    | '/voters'
    | '/candidates/$candidateId'
    | '/counties/$countyId'
    | '/districts/$districtId'
    | '/elections/$electionDate'
    | '/elections/$electionId'
    | '/invite/accept'
    | '/lookup/results'
    | '/voters/$voterId'
    | '/admin/'
    | '/elections/'
    | '/lookup/'
    | '/voters/'
    | '/admin/analysis/$runId'
    | '/admin/elections/$electionId'
    | '/admin/elections/create'
    | '/admin/elections/import-feed'
    | '/admin/users/create'
    | '/counties/$state/$county'
    | '/districts/$type/$name'
    | '/elections/$electionDate/$electionId'
    | '/admin/analysis/'
    | '/admin/elections/'
    | '/admin/exports/'
    | '/admin/geocoding/'
    | '/admin/imports/'
    | '/admin/users/'
    | '/elections/$electionDate/'
    | '/districts/$state/$type/$name'
    | '/districts/$state/$county/$type/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StateRoute: typeof StateRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ElectionsRoute: typeof ElectionsRouteWithChildren
  LoginRoute: typeof LoginRoute
  VotersRoute: typeof VotersRouteWithChildren
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  CountiesCountyIdRoute: typeof CountiesCountyIdRoute
  DistrictsDistrictIdRoute: typeof DistrictsDistrictIdRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  LookupResultsRoute: typeof LookupResultsRoute
  LookupIndexRoute: typeof LookupIndexRoute
  CountiesStateCountyRoute: typeof CountiesStateCountyRoute
  DistrictsTypeNameRoute: typeof DistrictsTypeNameRoute
  DistrictsStateTypeNameRoute: typeof DistrictsStateTypeNameRoute
  DistrictsStateCountyTypeNameRoute: typeof DistrictsStateCountyTypeNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voters': {
      id: '/voters'
      path: '/voters'
      fullPath: '/voters'
      preLoaderRoute: typeof VotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state': {
      id: '/$state'
      path: '/$state'
      fullPath: '/$state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voters/': {
      id: '/voters/'
      path: '/'
      fullPath: '/voters/'
      preLoaderRoute: typeof VotersIndexRouteImport
      parentRoute: typeof VotersRoute
    }
    '/lookup/': {
      id: '/lookup/'
      path: '/lookup'
      fullPath: '/lookup/'
      preLoaderRoute: typeof LookupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/': {
      id: '/elections/'
      path: '/'
      fullPath: '/elections/'
      preLoaderRoute: typeof ElectionsIndexRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/voters/$voterId': {
      id: '/voters/$voterId'
      path: '/$voterId'
      fullPath: '/voters/$voterId'
      preLoaderRoute: typeof VotersVoterIdRouteImport
      parentRoute: typeof VotersRoute
    }
    '/lookup/results': {
      id: '/lookup/results'
      path: '/lookup/results'
      fullPath: '/lookup/results'
      preLoaderRoute: typeof LookupResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/$electionId': {
      id: '/elections/$electionId'
      path: '/$electionId'
      fullPath: '/elections/$electionId'
      preLoaderRoute: typeof ElectionsElectionIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/elections/$electionDate': {
      id: '/elections/$electionDate'
      path: '/$electionDate'
      fullPath: '/elections/$electionDate'
      preLoaderRoute: typeof ElectionsElectionDateRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/districts/$districtId': {
      id: '/districts/$districtId'
      path: '/districts/$districtId'
      fullPath: '/districts/$districtId'
      preLoaderRoute: typeof DistrictsDistrictIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties/$countyId': {
      id: '/counties/$countyId'
      path: '/counties/$countyId'
      fullPath: '/counties/$countyId'
      preLoaderRoute: typeof CountiesCountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/$electionDate/': {
      id: '/elections/$electionDate/'
      path: '/'
      fullPath: '/elections/$electionDate/'
      preLoaderRoute: typeof ElectionsElectionDateIndexRouteImport
      parentRoute: typeof ElectionsElectionDateRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imports/': {
      id: '/admin/imports/'
      path: '/imports'
      fullPath: '/admin/imports/'
      preLoaderRoute: typeof AdminImportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geocoding/': {
      id: '/admin/geocoding/'
      path: '/geocoding'
      fullPath: '/admin/geocoding/'
      preLoaderRoute: typeof AdminGeocodingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports/': {
      id: '/admin/exports/'
      path: '/exports'
      fullPath: '/admin/exports/'
      preLoaderRoute: typeof AdminExportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/': {
      id: '/admin/elections/'
      path: '/elections'
      fullPath: '/admin/elections/'
      preLoaderRoute: typeof AdminElectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analysis/': {
      id: '/admin/analysis/'
      path: '/analysis'
      fullPath: '/admin/analysis/'
      preLoaderRoute: typeof AdminAnalysisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/elections/$electionDate/$electionId': {
      id: '/elections/$electionDate/$electionId'
      path: '/$electionId'
      fullPath: '/elections/$electionDate/$electionId'
      preLoaderRoute: typeof ElectionsElectionDateElectionIdRouteImport
      parentRoute: typeof ElectionsElectionDateRoute
    }
    '/districts/$type/$name': {
      id: '/districts/$type/$name'
      path: '/districts/$type/$name'
      fullPath: '/districts/$type/$name'
      preLoaderRoute: typeof DistrictsTypeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties/$state/$county': {
      id: '/counties/$state/$county'
      path: '/counties/$state/$county'
      fullPath: '/counties/$state/$county'
      preLoaderRoute: typeof CountiesStateCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/import-feed': {
      id: '/admin/elections/import-feed'
      path: '/elections/import-feed'
      fullPath: '/admin/elections/import-feed'
      preLoaderRoute: typeof AdminElectionsImportFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/create': {
      id: '/admin/elections/create'
      path: '/elections/create'
      fullPath: '/admin/elections/create'
      preLoaderRoute: typeof AdminElectionsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/$electionId': {
      id: '/admin/elections/$electionId'
      path: '/elections/$electionId'
      fullPath: '/admin/elections/$electionId'
      preLoaderRoute: typeof AdminElectionsElectionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analysis/$runId': {
      id: '/admin/analysis/$runId'
      path: '/analysis/$runId'
      fullPath: '/admin/analysis/$runId'
      preLoaderRoute: typeof AdminAnalysisRunIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/districts/$state/$type/$name': {
      id: '/districts/$state/$type/$name'
      path: '/districts/$state/$type/$name'
      fullPath: '/districts/$state/$type/$name'
      preLoaderRoute: typeof DistrictsStateTypeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$state/$county/$type/$name': {
      id: '/districts/$state/$county/$type/$name'
      path: '/districts/$state/$county/$type/$name'
      fullPath: '/districts/$state/$county/$type/$name'
      preLoaderRoute: typeof DistrictsStateCountyTypeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalysisRunIdRoute: typeof AdminAnalysisRunIdRoute
  AdminElectionsElectionIdRoute: typeof AdminElectionsElectionIdRoute
  AdminElectionsCreateRoute: typeof AdminElectionsCreateRoute
  AdminElectionsImportFeedRoute: typeof AdminElectionsImportFeedRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminAnalysisIndexRoute: typeof AdminAnalysisIndexRoute
  AdminElectionsIndexRoute: typeof AdminElectionsIndexRoute
  AdminExportsIndexRoute: typeof AdminExportsIndexRoute
  AdminGeocodingIndexRoute: typeof AdminGeocodingIndexRoute
  AdminImportsIndexRoute: typeof AdminImportsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalysisRunIdRoute: AdminAnalysisRunIdRoute,
  AdminElectionsElectionIdRoute: AdminElectionsElectionIdRoute,
  AdminElectionsCreateRoute: AdminElectionsCreateRoute,
  AdminElectionsImportFeedRoute: AdminElectionsImportFeedRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminAnalysisIndexRoute: AdminAnalysisIndexRoute,
  AdminElectionsIndexRoute: AdminElectionsIndexRoute,
  AdminExportsIndexRoute: AdminExportsIndexRoute,
  AdminGeocodingIndexRoute: AdminGeocodingIndexRoute,
  AdminImportsIndexRoute: AdminImportsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ElectionsElectionDateRouteChildren {
  ElectionsElectionDateElectionIdRoute: typeof ElectionsElectionDateElectionIdRoute
  ElectionsElectionDateIndexRoute: typeof ElectionsElectionDateIndexRoute
}

const ElectionsElectionDateRouteChildren: ElectionsElectionDateRouteChildren = {
  ElectionsElectionDateElectionIdRoute: ElectionsElectionDateElectionIdRoute,
  ElectionsElectionDateIndexRoute: ElectionsElectionDateIndexRoute,
}

const ElectionsElectionDateRouteWithChildren =
  ElectionsElectionDateRoute._addFileChildren(
    ElectionsElectionDateRouteChildren,
  )

interface ElectionsRouteChildren {
  ElectionsElectionDateRoute: typeof ElectionsElectionDateRouteWithChildren
  ElectionsElectionIdRoute: typeof ElectionsElectionIdRoute
  ElectionsIndexRoute: typeof ElectionsIndexRoute
}

const ElectionsRouteChildren: ElectionsRouteChildren = {
  ElectionsElectionDateRoute: ElectionsElectionDateRouteWithChildren,
  ElectionsElectionIdRoute: ElectionsElectionIdRoute,
  ElectionsIndexRoute: ElectionsIndexRoute,
}

const ElectionsRouteWithChildren = ElectionsRoute._addFileChildren(
  ElectionsRouteChildren,
)

interface VotersRouteChildren {
  VotersVoterIdRoute: typeof VotersVoterIdRoute
  VotersIndexRoute: typeof VotersIndexRoute
}

const VotersRouteChildren: VotersRouteChildren = {
  VotersVoterIdRoute: VotersVoterIdRoute,
  VotersIndexRoute: VotersIndexRoute,
}

const VotersRouteWithChildren =
  VotersRoute._addFileChildren(VotersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StateRoute: StateRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ElectionsRoute: ElectionsRouteWithChildren,
  LoginRoute: LoginRoute,
  VotersRoute: VotersRouteWithChildren,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  CountiesCountyIdRoute: CountiesCountyIdRoute,
  DistrictsDistrictIdRoute: DistrictsDistrictIdRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  LookupResultsRoute: LookupResultsRoute,
  LookupIndexRoute: LookupIndexRoute,
  CountiesStateCountyRoute: CountiesStateCountyRoute,
  DistrictsTypeNameRoute: DistrictsTypeNameRoute,
  DistrictsStateTypeNameRoute: DistrictsStateTypeNameRoute,
  DistrictsStateCountyTypeNameRoute: DistrictsStateCountyTypeNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
