/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LookupIndexRouteImport } from './routes/lookup/index'
import { Route as LookupResultsRouteImport } from './routes/lookup/results'
import { Route as CountiesCountyIdRouteImport } from './routes/counties/$countyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupIndexRoute = LookupIndexRouteImport.update({
  id: '/lookup/',
  path: '/lookup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupResultsRoute = LookupResultsRouteImport.update({
  id: '/lookup/results',
  path: '/lookup/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesCountyIdRoute = CountiesCountyIdRouteImport.update({
  id: '/counties/$countyId',
  path: '/counties/$countyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/lookup/results': typeof LookupResultsRoute
  '/lookup/': typeof LookupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/lookup/results': typeof LookupResultsRoute
  '/lookup': typeof LookupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/counties/$countyId': typeof CountiesCountyIdRoute
  '/lookup/results': typeof LookupResultsRoute
  '/lookup/': typeof LookupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/counties/$countyId'
    | '/lookup/results'
    | '/lookup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/counties/$countyId' | '/lookup/results' | '/lookup'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/counties/$countyId'
    | '/lookup/results'
    | '/lookup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CountiesCountyIdRoute: typeof CountiesCountyIdRoute
  LookupResultsRoute: typeof LookupResultsRoute
  LookupIndexRoute: typeof LookupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup/': {
      id: '/lookup/'
      path: '/lookup'
      fullPath: '/lookup/'
      preLoaderRoute: typeof LookupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup/results': {
      id: '/lookup/results'
      path: '/lookup/results'
      fullPath: '/lookup/results'
      preLoaderRoute: typeof LookupResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties/$countyId': {
      id: '/counties/$countyId'
      path: '/counties/$countyId'
      fullPath: '/counties/$countyId'
      preLoaderRoute: typeof CountiesCountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CountiesCountyIdRoute: CountiesCountyIdRoute,
  LookupResultsRoute: LookupResultsRoute,
  LookupIndexRoute: LookupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
